<?php /*

[MimeSettings]
MimeName[]
MimeName[text]=Text file
MimeName[page]=HTML or XML static page
MimeName[script]=Dynamic Html page or Script file
MimeName[pl]=Dynamic Perl Script file
MimeName[php]=Dynamic PHP Script file
MimeName[image]=Image
MimeName[document]=Document
MimeName[package]=Package
MimeName[archive]=Archive
MimeName[audio]=Audio file
MimeName[video]=Video file
MimeName[javascript]=JavaScript file
MimeName[vbs]=Visual Basic script
MimeName[conf]=Config file
MimeName[css]=Cascading Style Sheet file
MimeName[xsl]=Extensible Stylesheet Language file
MimeName[runtime]=Binary runtime
MimeName[library]=Binary library
MimeName[swf]=Macromedia Flash Animation
MimeName[dtd]=Document Type Definition
MimeName[csv]=Comma Separated Value file
MimeName[jnlp]=Java Web Start launch file
MimeName[lit]=Microsoft Reader e-book
MimeName[svg]=Scalable Vector Graphics
MimeName[ai]=Adobe Illustrator file
MimeName[phshop]=Adobe Photoshop image file
MimeName[ttf]=TrueType scalable font file
MimeName[fon]=Font file
MimeName[pdf]=Adobe Acrobat file

MimeFamily[]
MimeFamily[txt]=text
MimeFamily[log]=text
MimeFamily[html]=page
MimeFamily[htm]=page
MimeFamily[wml]=page
MimeFamily[wmlp]=page
MimeFamily[xhtml]=page
MimeFamily[xml]=page
MimeFamily[vak]=page
MimeFamily[sgm]=page
MimeFamily[sgml]=page
MimeFamily[asp]=script
MimeFamily[aspx]=script 
MimeFamily[asmx]=script 
MimeFamily[cfm]=script
MimeFamily[jsp]=script
MimeFamily[cgi]=script
MimeFamily[ksh]=script
MimeFamily[php]=php
MimeFamily[php3]=php
MimeFamily[php4]=php
MimeFamily[pl]=pl
MimeFamily[py]=script
MimeFamily[sh]=script
MimeFamily[shtml]=script
MimeFamily[tcl]=script
MimeFamily[xsp]=script
MimeFamily[gif]=image
MimeFamily[png]=image
MimeFamily[bmp]=image
MimeFamily[jpg]=image
MimeFamily[jpeg]=image
MimeFamily[cdr]=image
MimeFamily[ico]=image
MimeFamily[svg]=svg
MimeFamily[psd]=phshop
MimeFamily[ai]=ai
MimeFamily[doc]=document
MimeFamily[wmz]=document
MimeFamily[rtf]=document
MimeFamily[pdf]=pdf
MimeFamily[xls]=document
MimeFamily[ppt]=document
MimeFamily[pps]=document
MimeFamily[sxw]=document
MimeFamily[sxc]=document
MimeFamily[sxi]=document
MimeFamily[sxd]=document
MimeFamily[csv]=csv
MimeFamily[xsl]=xsl
MimeFamily[lit]=lit
MimeFamily[rpm]=package
MimeFamily[deb]=package
MimeFamily[msi]=package
MimeFamily[7z]=archive
MimeFamily[ace]=archive
MimeFamily[bz2]=archive
MimeFamily[gz]=archive
MimeFamily[jar]=archive
MimeFamily[rar]=archive
MimeFamily[tar]=archive
MimeFamily[tgz]=archive
MimeFamily[tbz2]=archive
MimeFamily[z]=archive
MimeFamily[zip]=archive
MimeFamily[mp3]=audio
MimeFamily[ogg]=audio
MimeFamily[wav]=audio
MimeFamily[wma]=audio
MimeFamily[avi]=video
MimeFamily[divx]=video
MimeFamily[mp4]=video
MimeFamily[mpeg]=video
MimeFamily[mpg]=video
MimeFamily[rm]=video
MimeFamily[swf]=swf
MimeFamily[wmv]=video
MimeFamily[mov]=video
MimeFamily[qt]=video
MimeFamily[js]=javascript
MimeFamily[vbs]=vbs
MimeFamily[cf]=conf
MimeFamily[conf]=conf
MimeFamily[css]=css
MimeFamily[ini]=conf
MimeFamily[dtd]=dtd
MimeFamily[exe]=runtime
MimeFamily[jnlp]=jnlp
MimeFamily[dll]=library
MimeFamily[ttf]=ttf
MimeFamily[fon]=fon


MimeIcon[]
MimeIcon[txt]=text
MimeIcon[log]=text
MimeIcon[html]=html
MimeIcon[htm]=html
MimeIcon[hdml]=html
MimeIcon[wml]=html
MimeIcon[wmlp]=html
MimeIcon[xhtml]=html
MimeIcon[xml]=html
MimeIcon[vak]=glasses
MimeIcon[sgm]=html
MimeIcon[sgml]=html
MimeIcon[asp]=script
MimeIcon[aspx]=script 
MimeIcon[asmx]=script 
MimeIcon[cfm]=script
MimeIcon[jsp]=script
MimeIcon[cgi]=script
MimeIcon[ksh]=script
MimeIcon[php]=php
MimeIcon[php3]=php
MimeIcon[php4]=php
MimeIcon[pl]=pl
MimeIcon[py]=script
MimeIcon[sh]=script
MimeIcon[shtml]=html
MimeIcon[tcl]=script
MimeIcon[xsp]=script
MimeIcon[gif]=image
MimeIcon[png]=image
MimeIcon[bmp]=image
MimeIcon[jpg]=image
MimeIcon[jpeg]=image
MimeIcon[cdr]=image
MimeIcon[ico]=image
MimeIcon[svg]=svg
MimeIcon[psd]=phshop
MimeIcon[doc]=doc
MimeIcon[wmz]=doc
MimeIcon[rtf]=doc
MimeIcon[pdf]=pdf
MimeIcon[xls]=xls
MimeIcon[ppt]=ppt
MimeIcon[pps]=ppt
MimeIcon[sxw]=other
MimeIcon[sxc]=other
MimeIcon[sxi]=other
MimeIcon[sxd]=other
MimeIcon[csv]=other
MimeIcon[xsl]=html
MimeIcon[lit]=lit
MimeIcon[ai]=ai
MimeIcon[rpm]=archive
MimeIcon[deb]=archive
MimeIcon[msi]=archive
MimeIcon[7z]=archive
MimeIcon[ace]=archive
MimeIcon[bz2]=archive
MimeIcon[gz]=archive
MimeIcon[jar]=archive
MimeIcon[rar]=archive
MimeIcon[tar]=archive
MimeIcon[tgz]=archive
MimeIcon[tbz2]=archive
MimeIcon[z]=archive
MimeIcon[zip]=archive
MimeIcon[mp3]=audio
MimeIcon[ogg]=audio
MimeIcon[wma]=audio
MimeIcon[wav]=audio
MimeIcon[avi]=video
MimeIcon[divx]=video
MimeIcon[mp4]=video
MimeIcon[mpeg]=video
MimeIcon[mpg]=video
MimeIcon[rm]=real
MimeIcon[swf]=flash
MimeIcon[wmv]=video
MimeIcon[mov]=quicktime
MimeIcon[qt]=quicktime
MimeIcon[js]=jscript
MimeIcon[vbs]=jscript
MimeIcon[cf]=other
MimeIcon[conf]=other
MimeIcon[css]=other
MimeIcon[ini]=other
MimeIcon[dtd]=other
MimeIcon[exe]=script
MimeIcon[dll]=script
MimeIcon[jnlp]=jnlp
MimeIcon[ttf]=ttf
MimeIcon[fon]=fon


*/ ?>
